### ISSUE TITLE
How I can disable server-side rendering for some pages?

### ISSUE THREAD

**Issue by kuatro** [janoist1/universal-react-redux-starter-kit#11]

**Comment by janoist1** [comment]
You can't really disable it for specific pages. What you can do is to implement those pages the way they don't render anything on server side but on client side you fire a `SOME_PAGE_START` action that you use for triggering client-only render..
Use `componentDidMount` to trigger an action which will result a page render on client side. Check [this](http://stackoverflow.com/questions/37439528/whats-the-best-way-to-run-function-logic-on-redux-app-start)
