### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by terencechow** [janoist1/universal-react-redux-starter-kit#15]
I am trying to convert my own project to universal. My project is based off the original davezuko starter kit. However I'm getting a window is not defined reference error with respect to the routes folder. Any reason why this might be?

**Comment by janoist1** [comment]
I guess thats because of the style loader relies on the DOM / window object. [check this](https://github.com/webpack/style-loader/blob/master/addStyles.js#L14)
And [this](https://www.npmjs.com/package/simple-universal-style-loader#server-environment).

**Comment by terencechow** [comment]
Thanks! I missed the simple-universal-style-loader when I was converting my project

**Comment by batusai513** [comment]
@terencechow how did you add this simple-universal-style-loader thing?, can you provide an example, thanks 👍
