### ISSUE TITLE
On Page Load, Route Gets Hit Twice

### ISSUE THREAD

**Issue by peterpme** [janoist1/universal-react-redux-starter-kit#18]
Hi there,

Thanks for putting this together! You're awesome!

On page load, the app will fire `app:server:universal:render Handl route` twice. 

The first time it fires, the params are correct.

The second time it fires, the params are `undefined`.

I'm trying to trace this out myself but it'd be great if you happened to run into the same issue.

Thanks,
Peter

**Comment by janoist1** [comment]
Thanks for reporting, I'll have a look.

**Comment by peterpme** [comment]
This was an issue on my end. Thanks!
