### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by berdof** [janoist1/universal-react-redux-starter-kit#2]
@janoist1 Tried to work with your fork. Currently it breaks on `npm run compile` with this error. `TypeError: Cannot read property 'src' of undefined
    at Object.<anonymous> (webpack.config.js:13:11)`

**Comment by janoist1** [comment]
Hi! Yes, I already run into this issue, but thanks for reporting it. So that I've started working on an improvement at the moment which will fix this one and also bring some extra benefits.. I keep you up to date.

**Comment by janoist1** [comment]
Hi, can you retry it? Pull master branch, npm install, etc.. If not working please let me know how exactly did you do it. Thanks
