### ISSUE TITLE
Warning: React attempted to reuse markup in a container...

### ISSUE THREAD

**Issue by peterpme** [janoist1/universal-react-redux-starter-kit#20]
Hey @janoist1!

Thanks again for your hard work!

I'm trying to figure out where this is coming from, but I'm constantly getting the following:

React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:

```

 (client) <div style="height:100%;"
 (server) <div data-reactroot="" da
```

I'm going to do my best to figure this out tonight, but just wanted to point out that without this working, we're not _technically_ server-rendering the right way.

Thanks again,
Peter

**Comment by janoist1** [comment]
Hi @peterpme !

I'm happy if you find this project useful.
How do you reproduce this issue? I had a very similar issue before but that was becuase the server was using a wrong rendering method.

Best,
Istvan

**Comment by peterpme** [comment]
Hey @janoist1 it turns out this had to do with React-resolver, which has also since been fixed!

Thanks again for the quick turnaround time, you rock!
