### ISSUE TITLE
client render issue

### ISSUE THREAD

**Issue by berdof** [janoist1/universal-react-redux-starter-kit#4]
Found one issue. I just realise that app is rerendered on client after js is loaded  http://take.ms/yv3Rs.
You can look how this is solved here https://github.com/erikras/react-redux-universal-hot-example .

**Comment by janoist1** [comment]
I didn't know that's an issue. What if you replace the `renderToStaticMarkup` with `renderToString` in the `src/server.js`. I have no other idea yet, but if you want I can queue this for you and come back later when the others are sorted. Or you can help me anytime ;-)

**Comment by janoist1** [comment]
Any luck with this?

**Comment by janoist1** [comment]
I've done some investigation and this is gonna be your issue .. I'll replace `renderToStaticMarkup` with `renderToString` in the future - But at the moment it's complaining about checksum mismatch if I do it ..

**Comment by berdof** [comment]
@janoist1 Also no luck. Stock with this( I think we are loosing benefits of server side rendering when app is completely rerendered on client. Maybe we can use some techniques from repo I mentioned earlier?

**Comment by janoist1** [comment]
What techniques you specifically mean?
Yesterday I tried switching to `renderToString` and that added some meta data to the output HTML so that the client can recognise it and decide wether is needs to be re-rendered or not. The only thing that holds me back now is a checksum error .. But I'll fix that and you can pull it very soon.

**Comment by fletcherist** [comment]
Hey, now working on this issue. Now the situation is terrible.

**Comment by janoist1** [comment]
@fletcherist, any luck ? I've been very busy in the past few days and looks like I'll be busy for the upcoming week too ... So, any progress would be much appreciated.

**Comment by fletcherist** [comment]
@janoist1 yeah, I have found out, that the problem probably might be in the miss match between the redux initial state of the server and client modules. So, I am trying to fix it now.

**Comment by bowenisdum** [comment]
any update on this issue?

**Comment by janoist1** [comment]
I have started investigating on it, turns out this issue is only on the `counter` page. Will keep you updated ..

**Comment by janoist1** [comment]
Oké, I've found out! The issue is because the `counter` uses code splitting. If you update your `src/routes/Counter/index.js` with the following:

``` javascript
import { injectReducer } from '../../store/reducers'
import CounterContainer from './containers/CounterContainer'

export default (store) => ({
  path: 'counter',
  component: CounterContainer,
  /*  Async getComponent is only invoked when route matches   */
  getComponent (nextState, cb) {
    /*  Webpack - use 'require.ensure' to create a split point
        and embed an async module loader (jsonp) when bundling   */
    require.ensure([], (require) => {
      /*  Webpack - use require callback to define
          dependencies for bundling   */
      const Counter = CounterContainer // require('./containers/CounterContainer').default
      const reducer = require('./modules/counter').default

      /*  Add the reducer to the store on key 'counter'  */
      injectReducer(store, { key: 'counter', reducer })

      /*  Return getComponent   */
      cb(null, Counter)

    /* Webpack named bundle   */
    }, 'counter')
  }
})
```

Then the issue will go away.
Also, you need to use `renderToString` instead of `renderToStaticMarkup` in your `src/server. js`. But I'm going to update this right now. Regarding the code splitting .. I'm not sure which direction to go: keep it and find a way to make it work or drop it ... Any suggestions are welcome.

**Comment by janoist1** [comment]
Found the final solution here: [http://stackoverflow.com/questions/37933571/react-attempted-to-reuse-markup-error-with-webpack-code-splitting](http://stackoverflow.com/questions/37933571/react-attempted-to-reuse-markup-error-with-webpack-code-splitting)
It is on master now. Happy coding!
