### ISSUE TITLE
serving through s3

### ISSUE THREAD

**Issue by bowenisdum** [janoist1/universal-react-redux-starter-kit#5]
with the react-redux-start-kit, the npm deploy generates the dist folder with the index.html with assets injected and built, it was possible to upload the dist folder to s3 and run the compiled app off s3. Is that no longer possible with this fork? do we need to run this off a node server?

**Comment by janoist1** [comment]
It is possible to do that if you turn off server-side rendering (`universal = false`) and build the project that way. But this would not make more sense since the key feature of this project is the SSR. If you need universal rendering you probably need to choose another service.

**Comment by bowenisdum** [comment]
thx! thats what we realized after digging around some more hehe.
