### ISSUE TITLE
missing index.html

### ISSUE THREAD

**Issue by chrisabrams** [janoist1/universal-react-redux-starter-kit#8]
When I run any of the build/compile steps, I do not get an index.html file in `dist`.

**Comment by fletcherist** [comment]
@chrisabrams, you should better run the compiled bundle through `npm start:prod`

**Comment by janoist1** [comment]
@chrisabrams, The index.html should be in the `dist/public` directory.

**Comment by chrisabrams** [comment]
Nope :/ No matter the command, I don't get an `index.html` file

**Comment by janoist1** [comment]
Have a look at the `universal.enabled` key in the `config/index.js` file. That should be turned `false` if you don't want SSR / universal rendering - This way the `index.html` will be there.

**Comment by chrisabrams** [comment]
OOOOOOOOOO - so when universal is enabled, no index.html is made because its using server.js. Got it ⭕ 

thanks #thread
