### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by chrisabrams** [janoist1/universal-react-redux-starter-kit#9]
When I try running the `npm start` command simply as `DEBUG=app:*; NODE_ENV=development; babel-node bin/server.js` I get this error.

**Comment by janoist1** [comment]
@chrisabrams, the correct way of starting up the application is:
- dev: `npm run dev`
- prod: `npm run deploy:prod && npm run start:prod`

Or just remove the `;` from your command :)

**Comment by chrisabrams** [comment]
Got it, thx!
